version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: pan-home.trueddns.com
      KC_DB_URL_PORT: 30745
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8082:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge
